---
- name: army_scout
  barrack_level: 1
  attack: 15
  energy: 100
  metal: 100
  crystal: 0
  gas: 0
  duration: 6
  race: 
  weapon: 
  critical: 0
  type: attack
- name: army_humen_1
  barrack_level: 1
  attack: 25
  energy: 80
  metal: 240
  crystal: 0
  gas: 0
  duration: 9
  race: humen
  weapon: assault
  critical: 5
  type: attack
- name: army_humen_2
  barrack_level: 5
  attack: 42
  energy: 160
  metal: 380
  crystal: 0
  gas: 0
  duration: 12
  race: humen
  weapon: snipe
  critical: 8
  type: attack
- name: army_light_1
  barrack_level: 9
  attack: 70
  energy: 310
  metal: 580
  crystal: 0
  gas: 0
  duration: 18
  race: light
  weapon: assault
  critical: 10
  type: attack
- name: army_light_2
  barrack_level: 13
  attack: 118
  energy: 600
  metal: 900
  crystal: 0
  gas: 0
  duration: 26
  race: light
  weapon: snipe
  critical: 12
  type: attack
- name: army_iron_1
  barrack_level: 17
  attack: 180
  energy: 1120
  metal: 1370
  crystal: 0
  gas: 0
  duration: 36
  race: iron
  weapon: assault
  critical: 20
  type: attack
- name: army_iron_2
  barrack_level: 21
  attack: 320
  energy: 2060
  metal: 2060
  crystal: 0
  gas: 0
  duration: 56
  race: iron
  weapon: snipe
  critical: 25
  type: attack
- name: army_iron_3
  barrack_level: 25
  attack: 480
  energy: 3780
  metal: 3100
  crystal: 0
  gas: 0
  duration: 80
  race: iron
  weapon: armor
  critical: 30
  type: attack
- name: army_rocket
  barrack_level: 5
  attack: 80
  energy: 0
  metal: 0
  gas: 120
  crystal: 464
  duration: 32
  race: 
  weapon: 
  critical: 0.0
  type: defend
- name: army_laser
  barrack_level: 15
  attack: 230
  energy: 0
  metal: 0
  gas: 1200
  crystal: 400
  duration: 40
  race: 
  weapon: 
  critical: 0.0
  type: defend
- name: army_ion
  barrack_level: 20
  attack: 600
  energy: 0
  metal: 0
  gas: 1760
  crystal: 2640
  duration: 56
  race: 
  weapon: 
  critical: 0.0
  type: defend
- name: army_mecha
  barrack_level: 15
  attack: 300
  energy: 0
  metal: 0
  gas: 3000
  crystal: 3000
  duration: 80
  race: 
  weapon: 
  critical: 0.0
  type: defend
