---
- level: 1
  name: gas_storage
  center_level: 8
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 10
- level: 2
  name: gas_storage
  center_level: 8
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 20
- level: 3
  name: gas_storage
  center_level: 8
  energy: 40
  crystal: 40
  metal: 0
  gas: 40
  duration: 30
- level: 4
  name: gas_storage
  center_level: 8
  energy: 50
  crystal: 50
  metal: 0
  gas: 50
  duration: 80
- level: 5
  name: gas_storage
  center_level: 8
  energy: 60
  crystal: 100
  metal: 0
  gas: 100
  duration: 180
- level: 6
  name: gas_storage
  center_level: 8
  energy: 100
  crystal: 260
  metal: 0
  gas: 260
  duration: 240
- level: 7
  name: gas_storage
  center_level: 8
  energy: 200
  crystal: 400
  metal: 0
  gas: 400
  duration: 420
- level: 8
  name: gas_storage
  center_level: 8
  energy: 200
  crystal: 500
  metal: 0
  gas: 500
  duration: 660
- level: 9
  name: gas_storage
  center_level: 9
  energy: 800
  crystal: 1800
  metal: 0
  gas: 1800
  duration: 1200
- level: 10
  name: gas_storage
  center_level: 10
  energy: 1200
  crystal: 2800
  metal: 0
  gas: 2800
  duration: 1600
- level: 11
  name: gas_storage
  center_level: 11
  energy: 4000
  crystal: 8600
  metal: 0
  gas: 8600
  duration: 2400
- level: 12
  name: gas_storage
  center_level: 12
  energy: 6000
  crystal: 12500
  metal: 0
  gas: 12500
  duration: 3000
- level: 13
  name: gas_storage
  center_level: 13
  energy: 12000
  crystal: 28000
  metal: 0
  gas: 28000
  duration: 4200
- level: 14
  name: gas_storage
  center_level: 14
  energy: 16000
  crystal: 38000
  metal: 0
  gas: 38000
  duration: 5000
- level: 15
  name: gas_storage
  center_level: 15
  energy: 40000
  crystal: 85000
  metal: 0
  gas: 85000
  duration: 7000
- level: 16
  name: gas_storage
  center_level: 16
  energy: 40000
  crystal: 100000
  metal: 0
  gas: 100000
  duration: 8800
- level: 17
  name: gas_storage
  center_level: 17
  energy: 80000
  crystal: 190000
  metal: 0
  gas: 190000
  duration: 10000
- level: 18
  name: gas_storage
  center_level: 18
  energy: 90000
  crystal: 250000
  metal: 0
  gas: 250000
  duration: 13000
- level: 19
  name: gas_storage
  center_level: 19
  energy: 180000
  crystal: 480000
  metal: 0
  gas: 480000
  duration: 16000
- level: 20
  name: gas_storage
  center_level: 20
  energy: 200000
  crystal: 500000
  metal: 0
  gas: 500000
  duration: 19000
- level: 21
  name: gas_storage
  center_level: 21
  energy: 300000
  crystal: 850000
  metal: 0
  gas: 850000
  duration: 26000
- level: 22
  name: gas_storage
  center_level: 22
  energy: 500000
  crystal: 1200000
  metal: 0
  gas: 1200000
  duration: 32000
- level: 23
  name: gas_storage
  center_level: 23
  energy: 600000
  crystal: 1600000
  metal: 0
  gas: 1600000
  duration: 38000
- level: 24
  name: gas_storage
  center_level: 24
  energy: 800000
  crystal: 2400000
  metal: 0
  gas: 2400000
  duration: 48000
- level: 25
  name: gas_storage
  center_level: 25
  energy: 1200000
  crystal: 3000000
  metal: 0
  gas: 3000000
  duration: 60000
- level: 26
  name: gas_storage
  center_level: 26
  energy: 1500000
  crystal: 4000000
  metal: 0
  gas: 4000000
  duration: 66000
- level: 27
  name: gas_storage
  center_level: 27
  energy: 1900000
  crystal: 5000000
  metal: 0
  gas: 5000000
  duration: 80000
- level: 28
  name: gas_storage
  center_level: 28
  energy: 2400000
  crystal: 6600000
  metal: 0
  gas: 6600000
  duration: 90000
- level: 29
  name: gas_storage
  center_level: 29
  energy: 4000000
  crystal: 9000000
  metal: 0
  gas: 9000000
  duration: 120000
- level: 30
  name: gas_storage
  center_level: 30
  energy: 6000000
  crystal: 13000000
  metal: 0
  gas: 13000000
  duration: 160000
