---
- level: 1
  name: metal
  center_level: 1
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 3
- level: 2
  name: metal
  center_level: 2
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 20
- level: 3
  name: metal
  center_level: 3
  energy: 40
  crystal: 40
  metal: 0
  gas: 40
  duration: 30
- level: 4
  name: metal
  center_level: 4
  energy: 50
  crystal: 50
  metal: 0
  gas: 50
  duration: 60
- level: 5
  name: metal
  center_level: 5
  energy: 60
  crystal: 70
  metal: 0
  gas: 80
  duration: 120
- level: 6
  name: metal
  center_level: 6
  energy: 100
  crystal: 150
  metal: 0
  gas: 200
  duration: 180
- level: 7
  name: metal
  center_level: 7
  energy: 200
  crystal: 400
  metal: 0
  gas: 400
  duration: 320
- level: 8
  name: metal
  center_level: 8
  energy: 200
  crystal: 440
  metal: 0
  gas: 440
  duration: 420
- level: 9
  name: metal
  center_level: 9
  energy: 600
  crystal: 1800
  metal: 0
  gas: 1800
  duration: 720
- level: 10
  name: metal
  center_level: 10
  energy: 1000
  crystal: 2800
  metal: 0
  gas: 2800
  duration: 1200
- level: 11
  name: metal
  center_level: 11
  energy: 3000
  crystal: 10000
  metal: 0
  gas: 10000
  duration: 1600
- level: 12
  name: metal
  center_level: 12
  energy: 4000
  crystal: 13000
  metal: 0
  gas: 13000
  duration: 2200
- level: 13
  name: metal
  center_level: 13
  energy: 10000
  crystal: 31000
  metal: 0
  gas: 31000
  duration: 2800
- level: 14
  name: metal
  center_level: 14
  energy: 10000
  crystal: 40000
  metal: 0
  gas: 40000
  duration: 3600
- level: 15
  name: metal
  center_level: 15
  energy: 30000
  crystal: 90000
  metal: 0
  gas: 90000
  duration: 4800
- level: 16
  name: metal
  center_level: 16
  energy: 30000
  crystal: 110000
  metal: 0
  gas: 110000
  duration: 5600
- level: 17
  name: metal
  center_level: 17
  energy: 60000
  crystal: 210000
  metal: 0
  gas: 210000
  duration: 7000
- level: 18
  name: metal
  center_level: 18
  energy: 80000
  crystal: 260000
  metal: 0
  gas: 260000
  duration: 9600
- level: 19
  name: metal
  center_level: 19
  energy: 130000
  crystal: 515000
  metal: 0
  gas: 515000
  duration: 12000
- level: 20
  name: metal
  center_level: 20
  energy: 140000
  crystal: 600000
  metal: 0
  gas: 600000
  duration: 14000
- level: 21
  name: metal
  center_level: 21
  energy: 200000
  crystal: 900000
  metal: 0
  gas: 900000
  duration: 18000
- level: 22
  name: metal
  center_level: 22
  energy: 300000
  crystal: 1300000
  metal: 0
  gas: 1300000
  duration: 22000
- level: 23
  name: metal
  center_level: 23
  energy: 400000
  crystal: 1800000
  metal: 0
  gas: 1800000
  duration: 26000
- level: 24
  name: metal
  center_level: 24
  energy: 600000
  crystal: 2400000
  metal: 0
  gas: 2400000
  duration: 34000
- level: 25
  name: metal
  center_level: 25
  energy: 800000
  crystal: 3200000
  metal: 0
  gas: 3200000
  duration: 40000
- level: 26
  name: metal
  center_level: 26
  energy: 1000000
  crystal: 4300000
  metal: 0
  gas: 4300000
  duration: 46000
- level: 27
  name: metal
  center_level: 27
  energy: 1500000
  crystal: 5000000
  metal: 0
  gas: 5000000
  duration: 52000
- level: 28
  name: metal
  center_level: 28
  energy: 1800000
  crystal: 7000000
  metal: 0
  gas: 7000000
  duration: 62000
- level: 29
  name: metal
  center_level: 29
  energy: 2400000
  crystal: 10000000
  metal: 0
  gas: 10000000
  duration: 80000
- level: 30
  name: metal
  center_level: 30
  energy: 3000000
  crystal: 13000000
  metal: 0
  gas: 13000000
  duration: 100000
