---
- level: 1
  name: factory
  center_level: 1
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 3
- level: 2
  name: factory
  center_level: 2
  energy: 40
  crystal: 40
  metal: 0
  gas: 40
  duration: 20
- level: 3
  name: factory
  center_level: 3
  energy: 50
  crystal: 50
  metal: 0
  gas: 50
  duration: 30
- level: 4
  name: factory
  center_level: 4
  energy: 60
  crystal: 60
  metal: 0
  gas: 60
  duration: 60
- level: 5
  name: factory
  center_level: 5
  energy: 60
  crystal: 80
  metal: 0
  gas: 80
  duration: 80
- level: 6
  name: factory
  center_level: 6
  energy: 70
  crystal: 120
  metal: 0
  gas: 120
  duration: 120
- level: 7
  name: factory
  center_level: 7
  energy: 100
  crystal: 300
  metal: 0
  gas: 300
  duration: 180
- level: 8
  name: factory
  center_level: 8
  energy: 120
  crystal: 400
  metal: 0
  gas: 400
  duration: 300
- level: 9
  name: factory
  center_level: 9
  energy: 200
  crystal: 500
  metal: 0
  gas: 500
  duration: 540
- level: 10
  name: factory
  center_level: 10
  energy: 240
  crystal: 800
  metal: 0
  gas: 800
  duration: 800
- level: 11
  name: factory
  center_level: 11
  energy: 600
  crystal: 2100
  metal: 0
  gas: 2100
  duration: 1080
- level: 12
  name: factory
  center_level: 12
  energy: 800
  crystal: 3000
  metal: 0
  gas: 3000
  duration: 1600
- level: 13
  name: factory
  center_level: 13
  energy: 1200
  crystal: 5000
  metal: 0
  gas: 5000
  duration: 1800
- level: 14
  name: factory
  center_level: 14
  energy: 1600
  crystal: 6000
  metal: 0
  gas: 6000
  duration: 2400
- level: 15
  name: factory
  center_level: 15
  energy: 3000
  crystal: 12000
  metal: 0
  gas: 12000
  duration: 3200
- level: 16
  name: factory
  center_level: 16
  energy: 3000
  crystal: 13500
  metal: 0
  gas: 13500
  duration: 4000
- level: 17
  name: factory
  center_level: 17
  energy: 6000
  crystal: 23500
  metal: 0
  gas: 23500
  duration: 4800
- level: 18
  name: factory
  center_level: 18
  energy: 8000
  crystal: 30000
  metal: 0
  gas: 30000
  duration: 6000
- level: 19
  name: factory
  center_level: 19
  energy: 12000
  crystal: 48000
  metal: 0
  gas: 48000
  duration: 8000
- level: 20
  name: factory
  center_level: 20
  energy: 12000
  crystal: 54000
  metal: 0
  gas: 54000
  duration: 9000
- level: 21
  name: factory
  center_level: 21
  energy: 18000
  crystal: 70000
  metal: 0
  gas: 70000
  duration: 12000
- level: 22
  name: factory
  center_level: 22
  energy: 24000
  crystal: 100000
  metal: 0
  gas: 100000
  duration: 16000
- level: 23
  name: factory
  center_level: 23
  energy: 30000
  crystal: 125000
  metal: 0
  gas: 125000
  duration: 18000
- level: 24
  name: factory
  center_level: 24
  energy: 40000
  crystal: 165000
  metal: 0
  gas: 165000
  duration: 24000
- level: 25
  name: factory
  center_level: 25
  energy: 50000
  crystal: 215000
  metal: 0
  gas: 215000
  duration: 28000
- level: 26
  name: factory
  center_level: 26
  energy: 80000
  crystal: 270000
  metal: 0
  gas: 270000
  duration: 32000
- level: 27
  name: factory
  center_level: 27
  energy: 80000
  crystal: 325000
  metal: 0
  gas: 325000
  duration: 36000
- level: 28
  name: factory
  center_level: 28
  energy: 100000
  crystal: 400000
  metal: 0
  gas: 400000
  duration: 42000
- level: 29
  name: factory
  center_level: 29
  energy: 140000
  crystal: 550000
  metal: 0
  gas: 550000
  duration: 54000
- level: 30
  name: factory
  center_level: 30
  energy: 180000
  crystal: 800000
  metal: 0
  gas: 800000
  duration: 64000
