---
- level: 1
  name: center
  center_level: 0
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 3
- level: 2
  name: center
  center_level: 1
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 20
- level: 3
  name: center
  center_level: 2
  energy: 40
  crystal: 40
  metal: 0
  gas: 40
  duration: 30
- level: 4
  name: center
  center_level: 3
  energy: 80
  crystal: 90
  metal: 0
  gas: 80
  duration: 120
- level: 5
  name: center
  center_level: 4
  energy: 80
  crystal: 200
  metal: 0
  gas: 200
  duration: 180
- level: 6
  name: center
  center_level: 5
  energy: 200
  crystal: 500
  metal: 0
  gas: 500
  duration: 320
- level: 7
  name: center
  center_level: 6
  energy: 300
  crystal: 1200
  metal: 0
  gas: 1200
  duration: 540
- level: 8
  name: center
  center_level: 7
  energy: 400
  crystal: 1400
  metal: 0
  gas: 1400
  duration: 800
- level: 9
  name: center
  center_level: 8
  energy: 1200
  crystal: 5000
  metal: 0
  gas: 5000
  duration: 1400
- level: 10
  name: center
  center_level: 9
  energy: 3000
  crystal: 8000
  metal: 0
  gas: 8000
  duration: 1860
- level: 11
  name: center
  center_level: 10
  energy: 10000
  crystal: 24000
  metal: 0
  gas: 24000
  duration: 2520
- level: 12
  name: center
  center_level: 11
  energy: 10000
  crystal: 40000
  metal: 0
  gas: 40000
  duration: 4000
- level: 13
  name: center
  center_level: 12
  energy: 20000
  crystal: 80000
  metal: 0
  gas: 80000
  duration: 5000
- level: 14
  name: center
  center_level: 13
  energy: 30000
  crystal: 120000
  metal: 0
  gas: 120000
  duration: 7000
- level: 15
  name: center
  center_level: 14
  energy: 60000
  crystal: 300000
  metal: 0
  gas: 300000
  duration: 8400
- level: 16
  name: center
  center_level: 15
  energy: 80000
  crystal: 320000
  metal: 0
  gas: 320000
  duration: 10000
- level: 17
  name: center
  center_level: 16
  energy: 150000
  crystal: 650000
  metal: 0
  gas: 650000
  duration: 12000
- level: 18
  name: center
  center_level: 17
  energy: 180000
  crystal: 800000
  metal: 0
  gas: 800000
  duration: 16000
- level: 19
  name: center
  center_level: 18
  energy: 500000
  crystal: 1600000
  metal: 0
  gas: 1600000
  duration: 20000
- level: 20
  name: center
  center_level: 19
  energy: 400000
  crystal: 1700000
  metal: 0
  gas: 1700000
  duration: 24000
- level: 21
  name: center
  center_level: 20
  energy: 600000
  crystal: 2600000
  metal: 0
  gas: 2600000
  duration: 32000
- level: 22
  name: center
  center_level: 21
  energy: 1000000
  crystal: 4000000
  metal: 0
  gas: 4000000
  duration: 40000
- level: 23
  name: center
  center_level: 22
  energy: 1200000
  crystal: 5000000
  metal: 0
  gas: 5000000
  duration: 46000
- level: 24
  name: center
  center_level: 23
  energy: 1800000
  crystal: 7000000
  metal: 0
  gas: 7000000
  duration: 56000
- level: 25
  name: center
  center_level: 24
  energy: 2400000
  crystal: 9000000
  metal: 0
  gas: 9000000
  duration: 70000
- level: 26
  name: center
  center_level: 25
  energy: 3000000
  crystal: 12000000
  metal: 0
  gas: 12000000
  duration: 80000
- level: 27
  name: center
  center_level: 26
  energy: 4000000
  crystal: 16000000
  metal: 0
  gas: 16000000
  duration: 90000
- level: 28
  name: center
  center_level: 27
  energy: 6000000
  crystal: 20000000
  metal: 0
  gas: 20000000
  duration: 120000
- level: 29
  name: center
  center_level: 28
  energy: 8000000
  crystal: 28000000
  metal: 0
  gas: 28000000
  duration: 140000
- level: 30
  name: center
  center_level: 29
  energy: 10000000
  crystal: 40000000
  metal: 0
  gas: 40000000
  duration: 190000
