---
- level: 1
  name: barrack
  center_level: 1
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 3
- level: 2
  name: barrack
  center_level: 2
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 20
- level: 3
  name: barrack
  center_level: 3
  energy: 30
  crystal: 30
  metal: 0
  gas: 40
  duration: 30
- level: 4
  name: barrack
  center_level: 4
  energy: 30
  crystal: 60
  metal: 0
  gas: 75
  duration: 70
- level: 5
  name: barrack
  center_level: 5
  energy: 30
  crystal: 120
  metal: 0
  gas: 130
  duration: 180
- level: 6
  name: barrack
  center_level: 6
  energy: 105
  crystal: 300
  metal: 0
  gas: 390
  duration: 310
- level: 7
  name: barrack
  center_level: 7
  energy: 200
  crystal: 600
  metal: 0
  gas: 600
  duration: 450
- level: 8
  name: barrack
  center_level: 8
  energy: 400
  crystal: 600
  metal: 0
  gas: 600
  duration: 600
- level: 9
  name: barrack
  center_level: 9
  energy: 2000
  crystal: 2000
  metal: 0
  gas: 2000
  duration: 900
- level: 10
  name: barrack
  center_level: 10
  energy: 2000
  crystal: 3500
  metal: 0
  gas: 4500
  duration: 1400
- level: 11
  name: barrack
  center_level: 11
  energy: 4000
  crystal: 12000
  metal: 0
  gas: 12000
  duration: 1800
- level: 12
  name: barrack
  center_level: 12
  energy: 6000
  crystal: 16000
  metal: 0
  gas: 16000
  duration: 3000
- level: 13
  name: barrack
  center_level: 13
  energy: 10000
  crystal: 38000
  metal: 0
  gas: 38000
  duration: 3600
- level: 14
  name: barrack
  center_level: 14
  energy: 20000
  crystal: 40000
  metal: 0
  gas: 40000
  duration: 4000
- level: 15
  name: barrack
  center_level: 15
  energy: 30000
  crystal: 100000
  metal: 0
  gas: 100000
  duration: 6000
- level: 16
  name: barrack
  center_level: 16
  energy: 40000
  crystal: 140000
  metal: 0
  gas: 140000
  duration: 7000
- level: 17
  name: barrack
  center_level: 17
  energy: 80000
  crystal: 230000
  metal: 0
  gas: 230000
  duration: 9000
- level: 18
  name: barrack
  center_level: 18
  energy: 100000
  crystal: 300000
  metal: 0
  gas: 300000
  duration: 12000
- level: 19
  name: barrack
  center_level: 19
  energy: 200000
  crystal: 650000
  metal: 0
  gas: 650000
  duration: 13000
- level: 20
  name: barrack
  center_level: 20
  energy: 200000
  crystal: 750000
  metal: 0
  gas: 750000
  duration: 16000
- level: 21
  name: barrack
  center_level: 21
  energy: 300000
  crystal: 1100000
  metal: 0
  gas: 1100000
  duration: 20000
- level: 22
  name: barrack
  center_level: 22
  energy: 400000
  crystal: 1600000
  metal: 0
  gas: 1600000
  duration: 26000
- level: 23
  name: barrack
  center_level: 23
  energy: 600000
  crystal: 2200000
  metal: 0
  gas: 2000000
  duration: 32000
- level: 24
  name: barrack
  center_level: 24
  energy: 800000
  crystal: 3100000
  metal: 0
  gas: 3100000
  duration: 40000
- level: 25
  name: barrack
  center_level: 25
  energy: 1000000
  crystal: 4300000
  metal: 0
  gas: 4300000
  duration: 46000
- level: 26
  name: barrack
  center_level: 26
  energy: 1400000
  crystal: 5600000
  metal: 0
  gas: 5600000
  duration: 55000
- level: 27
  name: barrack
  center_level: 27
  energy: 1800000
  crystal: 7000000
  metal: 0
  gas: 7000000
  duration: 64000
- level: 28
  name: barrack
  center_level: 28
  energy: 2400000
  crystal: 9500000
  metal: 0
  gas: 9500000
  duration: 73000
- level: 29
  name: barrack
  center_level: 29
  energy: 3300000
  crystal: 13500000
  metal: 0
  gas: 13500000
  duration: 93000
- level: 30
  name: barrack
  center_level: 30
  energy: 8000000
  crystal: 20000000
  metal: 0
  gas: 20000000
  duration: 120000
