---
- level: 1
  name: research
  center_level: 3
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 5
- level: 2
  name: research
  center_level: 3
  energy: 30
  crystal: 30
  metal: 0
  gas: 30
  duration: 20
- level: 3
  name: research
  center_level: 3
  energy: 50
  crystal: 50
  metal: 0
  gas: 50
  duration: 30
- level: 4
  name: research
  center_level: 4
  energy: 60
  crystal: 60
  metal: 0
  gas: 60
  duration: 80
- level: 5
  name: research
  center_level: 5
  energy: 70
  crystal: 80
  metal: 0
  gas: 80
  duration: 160
- level: 6
  name: research
  center_level: 6
  energy: 150
  crystal: 210
  metal: 0
  gas: 210
  duration: 240
- level: 7
  name: research
  center_level: 7
  energy: 240
  crystal: 420
  metal: 0
  gas: 420
  duration: 420
- level: 8
  name: research
  center_level: 8
  energy: 400
  crystal: 600
  metal: 0
  gas: 600
  duration: 600
- level: 9
  name: research
  center_level: 9
  energy: 1200
  crystal: 2200
  metal: 0
  gas: 2200
  duration: 1080
- level: 10
  name: research
  center_level: 10
  energy: 2000
  crystal: 3500
  metal: 0
  gas: 3500
  duration: 1500
- level: 11
  name: research
  center_level: 11
  energy: 8000
  crystal: 12000
  metal: 0
  gas: 12000
  duration: 2080
- level: 12
  name: research
  center_level: 12
  energy: 9000
  crystal: 16500
  metal: 0
  gas: 16500
  duration: 3000
- level: 13
  name: research
  center_level: 13
  energy: 20000
  crystal: 36500
  metal: 0
  gas: 36500
  duration: 4000
- level: 14
  name: research
  center_level: 14
  energy: 26000
  crystal: 50000
  metal: 0
  gas: 50000
  duration: 4800
- level: 15
  name: research
  center_level: 15
  energy: 60000
  crystal: 110000
  metal: 0
  gas: 110000
  duration: 6600
- level: 16
  name: research
  center_level: 16
  energy: 70000
  crystal: 130000
  metal: 0
  gas: 130000
  duration: 7680
- level: 17
  name: research
  center_level: 17
  energy: 150000
  crystal: 260000
  metal: 0
  gas: 260000
  duration: 9080
- level: 18
  name: research
  center_level: 18
  energy: 180000
  crystal: 320000
  metal: 0
  gas: 320000
  duration: 12000
- level: 19
  name: research
  center_level: 19
  energy: 320000
  crystal: 650000
  metal: 0
  gas: 650000
  duration: 16000
- level: 20
  name: research
  center_level: 20
  energy: 380000
  crystal: 700000
  metal: 0
  gas: 700000
  duration: 18000
- level: 21
  name: research
  center_level: 21
  energy: 600000
  crystal: 1200000
  metal: 0
  gas: 1200000
  duration: 24000
- level: 22
  name: research
  center_level: 22
  energy: 800000
  crystal: 2000000
  metal: 0
  gas: 2000000
  duration: 30000
- level: 23
  name: research
  center_level: 23
  energy: 1200000
  crystal: 2400000
  metal: 0
  gas: 2400000
  duration: 36000
- level: 24
  name: research
  center_level: 24
  energy: 1600000
  crystal: 3000000
  metal: 0
  gas: 3000000
  duration: 44000
- level: 25
  name: research
  center_level: 25
  energy: 2000000
  crystal: 3900000
  metal: 0
  gas: 3900000
  duration: 54000
- level: 26
  name: research
  center_level: 26
  energy: 2800000
  crystal: 5000000
  metal: 0
  gas: 5000000
  duration: 66000
- level: 27
  name: research
  center_level: 27
  energy: 4000000
  crystal: 7000000
  metal: 0
  gas: 7000000
  duration: 72000
- level: 28
  name: research
  center_level: 28
  energy: 5000000
  crystal: 9000000
  metal: 0
  gas: 9000000
  duration: 80000
- level: 29
  name: research
  center_level: 29
  energy: 7000000
  crystal: 12000000
  metal: 0
  gas: 12000000
  duration: 120000
- level: 30
  name: research
  center_level: 30
  energy: 10000000
  crystal: 20000000
  metal: 0
  gas: 20000000
  duration: 24000
