---
- level: 1
  defend_might: 1000
  defend_armies:
    - army_humen_2
  defend_columns: 1
  reward_resource: 2200
  reward_might: 0
  reward_hero_rate:
  reward_item_rate: 0
  reward_army_races: ''
- level: 2
  defend_might: 7500
  defend_armies:
    - army_humen_1
    - army_humen_2
  defend_columns: 1
  reward_resource: 10000
  reward_might: 0
  reward_hero_rate:
  reward_item_rate: 0
  reward_army_races: ''
- level: 3
  defend_might: 15000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
  defend_columns: 2
  reward_resource: 22500
  reward_might: 1000
  reward_hero_rate:
  reward_item_rate: 0
  reward_army_races: humen
- level: 4
  defend_might: 30000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
  defend_columns: 2
  reward_resource: 45000
  reward_might: 2000
  reward_hero_rate:
  reward_item_rate: 0
  reward_army_races:
    - humen
    - iron
    - light
- level: 5
  defend_might: 100000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
    - army_iron_1
  defend_columns: 2
  reward_resource: 90000
  reward_might: 3000
  reward_hero_rate:
    star: 1
    rate: 5
  reward_item_rate: 0
  reward_army_races:
    - humen
    - iron
    - light
- level: 6
  defend_might: 250000
  defend_armies:
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
    - army_iron_3
  defend_columns: 3
  reward_resource: 180000
  reward_might: 6000
  reward_hero_rate:
    star: 1
    rate: 10
  reward_item_rate: 1
  reward_army_races:
    - humen
    - iron
    - light
- level: 7
  defend_might: 1000000
  defend_armies:
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
    - army_iron_3
  defend_columns: 3
  reward_resource: 350000
  reward_might: 6000
  reward_hero_rate:
    star: 2
    rate: 5
  reward_item_rate: 2
  reward_army_races:
    - humen
    - iron
    - light
- level: 8
  defend_might: 3000000
  defend_armies:
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
    - army_iron_3
  defend_columns: 3
  reward_resource: 600000
  reward_might: 6600
  reward_hero_rate:
    star: 2
    rate: 10
  reward_item_rate: 2
  reward_army_races:
    - humen
    - iron
    - light
- level: 9
  defend_might: 8000000
  defend_armies:
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
    - army_iron_3
  defend_columns: 3
  reward_resource: 780000
  reward_might: 7000
  reward_hero_rate:
    star: 3
    rate: 1
  reward_item_rate: 3
  reward_army_races:
    - humen
    - iron
    - light
- level: 10
  defend_might: 16000000
  defend_armies:
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
    - army_iron_3
  defend_columns: 3
  reward_resource: 960000
  reward_might: 8000
  reward_hero_rate:
    star: 4
    rate: 0.1
  reward_item_rate: 3
  reward_army_races:
    - humen
    - iron
    - light
