---
- center_level: 1
  factory_level: 1
  factory_amount: 1
  worker_amount: 30
- center_level: 2
  factory_level: 2
  factory_amount: 1
  worker_amount: 45
- center_level: 3
  factory_level: 3
  factory_amount: 2
  worker_amount: 60
- center_level: 4
  factory_level: 4
  factory_amount: 2
  worker_amount: 75
- center_level: 5
  factory_level: 5
  factory_amount: 2
  worker_amount: 90
- center_level: 6
  factory_level: 6
  factory_amount: 2
  worker_amount: 105
- center_level: 7
  factory_level: 7
  factory_amount: 2
  worker_amount: 120
- center_level: 8
  factory_level: 8
  factory_amount: 3
  worker_amount: 135
- center_level: 9
  factory_level: 9
  factory_amount: 4
  worker_amount: 150
- center_level: 10
  factory_level: 10
  factory_amount: 5
  worker_amount: 165
- center_level: 11
  factory_level: 11
  factory_amount: 6
  worker_amount: 180
- center_level: 12
  factory_level: 12
  factory_amount: 7
  worker_amount: 195
- center_level: 13
  factory_level: 13
  factory_amount: 8
  worker_amount: 210
- center_level: 14
  factory_level: 14
  factory_amount: 9
  worker_amount: 225
- center_level: 15
  factory_level: 15
  factory_amount: 10
  worker_amount: 240
- center_level: 16
  factory_level: 16
  factory_amount: 11
  worker_amount: 255
- center_level: 17
  factory_level: 17
  factory_amount: 12
  worker_amount: 270
- center_level: 18
  factory_level: 18
  factory_amount: 13
  worker_amount: 285
- center_level: 19
  factory_level: 19
  factory_amount: 14
  worker_amount: 300
- center_level: 20
  factory_level: 20
  factory_amount: 15
  worker_amount: 315
- center_level: 21
  factory_level: 21
  factory_amount: 16
  worker_amount: 330
- center_level: 22
  factory_level: 22
  factory_amount: 17
  worker_amount: 345
- center_level: 23
  factory_level: 23
  factory_amount: 18
  worker_amount: 360
- center_level: 24
  factory_level: 24
  factory_amount: 19
  worker_amount: 375
- center_level: 25
  factory_level: 25
  factory_amount: 20
  worker_amount: 390
- center_level: 26
  factory_level: 26
  factory_amount: 21
  worker_amount: 405
- center_level: 27
  factory_level: 27
  factory_amount: 22
  worker_amount: 420
- center_level: 28
  factory_level: 28
  factory_amount: 23
  worker_amount: 435
- center_level: 29
  factory_level: 29
  factory_amount: 24
  worker_amount: 450
- center_level: 30
  factory_level: 30
  factory_amount: 25
  worker_amount: 465
