---
- level: 1
  defend_might: 50
  defend_armies:
    - army_humen_1
    - army_humen_2
  bonus_percent: 5
  scout_level: 1
  scout_might: 25
- level: 2
  defend_might: 200
  defend_armies:
    - army_humen_1
    - army_humen_2
  bonus_percent: 10
  scout_level: 3
  scout_might: 100
- level: 3
  defend_might: 400
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
  bonus_percent: 15
  scout_level: 5
  scout_might: 200
- level: 4
  defend_might: 800
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
  bonus_percent: 20
  scout_level: 7
  scout_might: 400
- level: 5
  defend_might: 4000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
  bonus_percent: 25
  scout_level: 9
  scout_might: 2000
- level: 6
  defend_might: 20000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
  bonus_percent: 30
  scout_level: 11
  scout_might: 4000
- level: 7
  defend_might: 40000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
    - army_iron_1
  bonus_percent: 35
  scout_level: 13
  scout_might: 8000
- level: 8
  defend_might: 100000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
    - army_iron_1
  bonus_percent: 40
  scout_level: 15
  scout_might: 12000
- level: 9
  defend_might: 200000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
  bonus_percent: 45
  scout_level: 17
  scout_might: 16000
- level: 10
  defend_might: 600000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
  bonus_percent: 50
  scout_level: 19
  scout_might: 20000
- level: 11
  defend_might: 1200000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
    - army_iron_3
  bonus_percent: 55
  scout_level: 21
  scout_might: 24000
- level: 12
  defend_might: 2400000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
    - army_iron_3
  bonus_percent: 60
  scout_level: 23
  scout_might: 28000
- level: 13
  defend_might: 4800000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
    - army_iron_3
  bonus_percent: 65
  scout_level: 25
  scout_might: 32000
- level: 14
  defend_might: 9600000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
    - army_iron_3
  bonus_percent: 70
  scout_level: 27
  scout_might: 36000
- level: 15
  defend_might: 12000000
  defend_armies:
    - army_humen_1
    - army_humen_2
    - army_light_1
    - army_light_2
    - army_iron_1
    - army_iron_2
    - army_iron_3
  bonus_percent: 75
  scout_level: 29
  scout_might: 40000
