---
- level: 1
  workers: 10
- level: 2
  workers: 15
- level: 3
  workers: 30
- level: 4
  workers: 40
- level: 5
  workers: 50
- level: 6
  workers: 60
- level: 7
  workers: 70
- level: 8
  workers: 130
- level: 9
  workers: 190
- level: 10
  workers: 270
- level: 11
  workers: 350
- level: 12
  workers: 450
- level: 13
  workers: 550
- level: 14
  workers: 670
- level: 15
  workers: 790
- level: 16
  workers: 940
- level: 17
  workers: 1090
- level: 18
  workers: 1240
- level: 19
  workers: 1390
- level: 20
  workers: 1590
- level: 21
  workers: 1740
- level: 22
  workers: 1990
- level: 23
  workers: 2140
- level: 24
  workers: 2390
- level: 25
  workers: 2590
- level: 26
  workers: 2840
- level: 27
  workers: 3090
- level: 28
  workers: 3340
- level: 29
  workers: 3590
- level: 30
  workers: 3890
