---
- name: building_center
  requirements:
    building_research: -1
- name: building_research
  requirements:
    building_energy: -1
    building_barrack: -1
    building_center: 0
- name: building_barrack
  requirements:
    building_metal: 0
    building_crystal: 0
    building_gas: 0
- name: building_energy
  requirements:
    building_center: 0
- name: building_metal
  requirements:
    building_metal_storage: -1
- name: building_gas
  requirements:
    building_gas_storage: -1
- name: building_crystal
  requirements:
    building_crystal_storage: -1
- name: building_metal_storage
  requirements:
    building_center: 0
- name: building_crystal_storage
  requirements:
    building_center: 0
- name: building_gas_storage
  requirements:
    building_center: 0
- name: building_transform
  requirements:
    building_center: 0
- name: building_factory
  requirements:
    building_center: 0
